### ISSUE TITLE
New conference: ConFrontJS 2018

### ISSUE THREAD

**Issue by piecioshka** [CorpGlory/dataconfs#5]
Details:

* Website: https://confrontjs.com
* Location: Warsaw, Poland
* Date: 2018-10-29
* Registration: https://eventil.com/events/confrontjs-2018
* Call for Proposals: https://eventil.com/events/confrontjs-2018/cfp
* Twitter: @confrontjs
* Twitter Hashtag: #confrontjs

**Comment by jonyrock** [comment]
hey 
@piecioshka we are interested in data-related confs only. 
But thank you for info.

**Comment by piecioshka** [comment]
Ok, thanks! No problem 😄
